"""
html_renderer.py — 将分析结果渲染为 HTML 小论文

接收 LLMSkillAgent 输出的结构化数据，生成包含文本、表格、
ECharts 图表的单文件 HTML 报告。
"""

from __future__ import annotations

import json
from typing import Any

# ---------------------------------------------------------------------------
# HTML 模板常量
# ---------------------------------------------------------------------------

_HTML_BOILERPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: "Noto Serif SC", Georgia, serif;
    font-size: 15px;
    line-height: 1.8;
    color: #222;
    background: #fafafa;
    padding: 32px 16px;
  }}
  .paper {{
    max-width: 900px;
    margin: 0 auto;
    background: #fff;
    border: 1px solid #e0e0e0;
    border-radius: 6px;
    padding: 48px 56px;
  }}
  h1 {{ font-size: 1.75em; text-align: center; margin-bottom: 6px; }}
  .meta {{ text-align: center; color: #666; font-size: 0.9em; margin-bottom: 32px; }}
  h2 {{ font-size: 1.25em; border-bottom: 2px solid #333; padding-bottom: 4px;
        margin: 32px 0 12px; }}
  h3 {{ font-size: 1.05em; margin: 20px 0 8px; color: #444; }}
  p {{ margin-bottom: 10px; text-align: justify; }}
  ul, ol {{ margin: 8px 0 12px 24px; }}
  li {{ margin-bottom: 4px; }}
  table {{
    width: 100%; border-collapse: collapse;
    font-size: 0.9em; margin: 16px 0;
  }}
  th {{
    background: #f0f0f0; font-weight: 600;
    border: 1px solid #ccc; padding: 8px 12px; text-align: left;
  }}
  td {{
    border: 1px solid #ddd; padding: 7px 12px;
    vertical-align: top;
  }}
  tr:nth-child(even) td {{ background: #fafafa; }}
  .chart-container {{
    width: 100%; height: 360px; margin: 20px 0;
  }}
  .note {{
    background: #fffbe6; border-left: 4px solid #f0b429;
    padding: 10px 14px; margin: 16px 0; font-size: 0.9em;
    border-radius: 2px;
  }}
  .badge {{
    display: inline-block; padding: 2px 8px; border-radius: 10px;
    font-size: 0.8em; font-weight: 600; margin: 2px;
  }}
  .badge-high {{ background: #ffeaea; color: #c0392b; }}
  .badge-medium {{ background: #fff3cd; color: #856404; }}
  .badge-low {{ background: #e8f5e9; color: #2e7d32; }}
  .toc {{ margin-bottom: 32px; padding: 16px; background: #f8f9fa;
           border-radius: 4px; }}
  .toc ul {{ list-style: none; margin: 0; padding: 0; }}
  .toc li {{ margin: 4px 0; }}
  .toc a {{ color: #1a73e8; text-decoration: none; }}
  .toc a:hover {{ text-decoration: underline; }}
  footer {{ margin-top: 48px; padding-top: 16px; border-top: 1px solid #eee;
             font-size: 0.85em; color: #888; text-align: center; }}
  .references {{ margin-top: 32px; padding-top: 16px; border-top: 2px solid #333; }}
  .references ol {{ margin: 8px 0 0 20px; padding: 0; font-size: 0.88em;
                    color: #444; line-height: 1.9; }}
  .references ol li {{ margin-bottom: 2px; }}
  .ref-id {{ color: #1a73e8; font-weight: 600; }}
  sup.cite {{ font-size: 0.75em; color: #1a73e8; font-weight: 600;
              vertical-align: super; line-height: 0; }}
</style>
</head>
<body>
<div class="paper">
{body}
<footer>Generated by KGAnalysis · {rq_id} · {timestamp}</footer>
</div>
</body>
</html>"""


# ---------------------------------------------------------------------------
# 辅助生成器
# ---------------------------------------------------------------------------

def _esc(text: str) -> str:
    """HTML 转义。"""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _render_text(text: str) -> str:
    """
    HTML 转义后，将正文中的 [N] 引用标注转为上标链接。
    例如：「AGENTPOISON [1] 是...」→ 「AGENTPOISON <sup class="cite"><a href="#ref-1">[1]</a></sup> 是...」
    """
    import re
    escaped = _esc(text)
    # 匹配 [数字] 或 [数字,数字,...] 形式
    def _replace(m: re.Match) -> str:
        nums = re.findall(r"\d+", m.group(0))
        sups = "".join(
            f'<sup class="cite"><a href="#ref-{n}" style="text-decoration:none">[{n}]</a></sup>'
            for n in nums
        )
        return sups
    return re.sub(r"\[[\d,\s]+\]", _replace, escaped)


def render_table(headers: list[str], rows: list[list[Any]]) -> str:
    """生成 HTML 表格。"""
    th = "".join(f"<th>{_esc(h)}</th>" for h in headers)
    body_rows = ""
    for row in rows:
        tds = "".join(f"<td>{_esc(cell)}</td>" for cell in row)
        body_rows += f"<tr>{tds}</tr>\n"
    return f"<table><thead><tr>{th}</tr></thead><tbody>{body_rows}</tbody></table>"


def render_bar_chart(
    chart_id: str,
    title: str,
    categories: list[str],
    series_name: str,
    values: list[int | float],
    *,
    color: str = "#5470c6",
    height: int = 360,
) -> str:
    """生成 ECharts 柱状图 HTML 片段。"""
    option = {
        "title": {"text": title, "textStyle": {"fontSize": 14}},
        "tooltip": {"trigger": "axis"},
        "xAxis": {
            "type": "category",
            "data": categories,
            "axisLabel": {"rotate": 30, "interval": 0},
        },
        "yAxis": {"type": "value"},
        "series": [{"name": series_name, "type": "bar",
                     "data": values, "itemStyle": {"color": color}}],
        "grid": {"left": "8%", "right": "4%", "bottom": "18%", "top": "15%"},
    }
    option_json = json.dumps(option, ensure_ascii=False)
    return (
        f'<div id="{chart_id}" class="chart-container" style="height:{height}px"></div>\n'
        f"<script>\n"
        f"(function(){{\n"
        f"  var c = echarts.init(document.getElementById('{chart_id}'));\n"
        f"  c.setOption({option_json});\n"
        f"  window.addEventListener('resize', function(){{ c.resize(); }});\n"
        f"}})();\n"
        f"</script>"
    )


def render_pie_chart(
    chart_id: str,
    title: str,
    data: list[dict[str, Any]],  # [{"name": ..., "value": ...}]
    *,
    height: int = 340,
) -> str:
    """生成 ECharts 饼图 HTML 片段。"""
    option = {
        "title": {"text": title, "textStyle": {"fontSize": 14},
                  "left": "center"},
        "tooltip": {"trigger": "item", "formatter": "{b}: {c} ({d}%)"},
        "legend": {"orient": "vertical", "left": "left"},
        "series": [{"name": title, "type": "pie", "radius": "55%",
                    "data": data, "emphasis": {"itemStyle": {
                        "shadowBlur": 10, "shadowOffsetX": 0,
                        "shadowColor": "rgba(0,0,0,0.5)"}}}],
    }
    option_json = json.dumps(option, ensure_ascii=False)
    return (
        f'<div id="{chart_id}" class="chart-container" style="height:{height}px"></div>\n'
        f"<script>\n"
        f"(function(){{\n"
        f"  var c = echarts.init(document.getElementById('{chart_id}'));\n"
        f"  c.setOption({option_json});\n"
        f"  window.addEventListener('resize', function(){{ c.resize(); }});\n"
        f"}})();\n"
        f"</script>"
    )


# ---------------------------------------------------------------------------
# HTMLReport — 逐步构建报告 DOM
# ---------------------------------------------------------------------------

class HTMLReport:
    """
    可逐步追加内容的 HTML 报告构建器。

    Usage:
        report = HTMLReport("报告标题", rq_id="RQ-001")
        report.add_section("研究背景", "<p>...</p>")
        report.add_table("数据统计", headers=[...], rows=[...])
        report.add_bar_chart("chart1", "分布图", categories=[...], values=[...])
        html = report.build()
    """

    def __init__(self, title: str, rq_id: str = "", meta_info: str = "") -> None:
        self.title = title
        self.rq_id = rq_id
        self.meta_info = meta_info
        self._sections: list[tuple[str, str]] = []  # (anchor_id, html_content)
        self._toc_entries: list[tuple[str, str]] = []  # (anchor_id, display_text)
        self._chart_counter = 0

    def _next_chart_id(self) -> str:
        self._chart_counter += 1
        return f"chart_{self._chart_counter}"

    def add_section(self, heading: str, html_content: str, level: int = 2) -> "HTMLReport":
        """添加一个章节（带标题和任意 HTML 内容）。"""
        anchor = "sec_" + re.sub(r"\W+", "_", heading).strip("_")
        tag = f"h{level}"
        block = (
            f'<{tag} id="{anchor}">{_esc(heading)}</{tag}>\n'
            f"{html_content}\n"
        )
        self._sections.append((anchor, block))
        if level == 2:
            self._toc_entries.append((anchor, heading))
        return self

    def add_paragraph(self, text: str) -> "HTMLReport":
        """在最后一个章节后追加段落（不加标题）。"""
        if self._sections:
            anchor, content = self._sections[-1]
            self._sections[-1] = (anchor, content + f"<p>{_esc(text)}</p>\n")
        return self

    def add_table(
        self,
        caption: str,
        headers: list[str],
        rows: list[list[Any]],
    ) -> "HTMLReport":
        """在最后一个章节中添加表格（带小标题）。"""
        html = f"<h3>{_esc(caption)}</h3>\n" + render_table(headers, rows)
        if self._sections:
            anchor, content = self._sections[-1]
            self._sections[-1] = (anchor, content + html + "\n")
        return self

    def add_bar_chart(
        self,
        title: str,
        categories: list[str],
        series_name: str,
        values: list[int | float],
        **kwargs: Any,
    ) -> "HTMLReport":
        """在最后一个章节中添加柱状图。"""
        chart_id = self._next_chart_id()
        html = render_bar_chart(chart_id, title, categories, series_name, values, **kwargs)
        if self._sections:
            anchor, content = self._sections[-1]
            self._sections[-1] = (anchor, content + html + "\n")
        return self

    def add_pie_chart(
        self,
        title: str,
        data: list[dict[str, Any]],
        **kwargs: Any,
    ) -> "HTMLReport":
        """在最后一个章节中添加饼图。"""
        chart_id = self._next_chart_id()
        html = render_pie_chart(chart_id, title, data, **kwargs)
        if self._sections:
            anchor, content = self._sections[-1]
            self._sections[-1] = (anchor, content + html + "\n")
        return self

    def add_note(self, text: str) -> "HTMLReport":
        """添加高亮提示块。"""
        html = f'<div class="note">{_render_text(text)}</div>\n'
        if self._sections:
            anchor, content = self._sections[-1]
            self._sections[-1] = (anchor, content + html)
        return self

    def add_references(
        self,
        entries: list[dict],  # [{"id": 1, "paper_id": "...", "title": "..."}]
    ) -> "HTMLReport":
        """添加参考文献列表（报告末尾）。"""
        if not entries:
            return self
        items = ""
        for e in entries:
            ref_id = _esc(str(e.get("id", "")))
            paper_id = _esc(str(e.get("paper_id", "")))
            title = _esc(str(e.get("title", paper_id)))
            paper_id_code = (
                f'&nbsp;<code style="font-size:0.82em;color:#888">{paper_id}</code>'
                if paper_id and paper_id != title
                else ""
            )
            items += (
                f'<li id="ref-{ref_id}" style="margin-bottom:4px">'
                f'<span class="ref-id">[{ref_id}]</span>&nbsp;'
                f'{title}{paper_id_code}'
                f'</li>\n'
            )
        html = (
            f'<div class="references">'
            f'<h2 id="sec_references">参考文献</h2>'
            f'<ol style="list-style:none;padding:0">{items}</ol>'
            f'</div>\n'
        )
        self._sections.append(("sec_references", html))
        return self

    def build(self) -> str:
        """生成完整 HTML 字符串。"""
        from datetime import datetime

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

        # 标题 + 元信息
        header_html = (
            f"<h1>{_esc(self.title)}</h1>\n"
            f'<div class="meta">{_esc(self.meta_info)}</div>\n'
            if self.meta_info
            else f"<h1>{_esc(self.title)}</h1>\n"
        )

        # 目录
        toc_html = ""
        if self._toc_entries:
            items = "".join(
                f'<li><a href="#{aid}">{_esc(text)}</a></li>\n'
                for aid, text in self._toc_entries
            )
            toc_html = f'<nav class="toc"><strong>目录</strong><ul>{items}</ul></nav>\n'

        body = header_html + toc_html + "\n".join(c for _, c in self._sections)

        return _HTML_BOILERPLATE.format(
            title=_esc(self.title),
            body=body,
            rq_id=_esc(self.rq_id),
            timestamp=timestamp,
        )

    def save(self, path: str) -> None:
        """写入 HTML 文件。"""
        import os
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.build())


# ---------------------------------------------------------------------------
# 从 LLM 输出自动渲染（解析 LLM 返回的结构化 sections）
# ---------------------------------------------------------------------------

def render_from_llm_output(
    llm_sections: list[dict[str, Any]],
    title: str,
    rq_id: str = "",
    meta_info: str = "",
) -> str:
    """
    将 LLM 输出的 sections 列表渲染为 HTML。

    llm_sections 格式（LLM 生成的 JSON 数组）：
    [
      {
        "type": "section",
        "heading": "研究背景",
        "content": "..."           ← 正文文本
      },
      {
        "type": "table",
        "heading": "数据统计",
        "headers": ["列1","列2"],
        "rows": [["v1","v2"], ...]
      },
      {
        "type": "bar_chart",
        "heading": "分布图",
        "categories": ["A","B","C"],
        "series_name": "数量",
        "values": [10, 5, 3]
      },
      {
        "type": "pie_chart",
        "heading": "占比分布",
        "data": [{"name":"A","value":10}, ...]
      },
      {
        "type": "note",
        "content": "注意：..."
      }
    ]
    """
    report = HTMLReport(title, rq_id=rq_id, meta_info=meta_info)

    for item in llm_sections:
        item_type = item.get("type", "section")
        heading = item.get("heading", "")

        if item_type == "section":
            content_raw = item.get("content", "")
            # 换行转段落，每段用 _render_text 处理引用标注
            paras = content_raw.split("\n")
            content_html = "".join(
                f"<p>{_render_text(p)}</p>" for p in paras if p.strip()
            )
            report.add_section(heading, content_html)

        elif item_type == "table":
            if not heading:
                heading = item.get("caption", "数据表")
            # 先建一个空 section 再加表（保证 caption 层级正确）
            if not report._sections or report._sections[-1][0].startswith("sec_"):
                pass  # 追加到当前章节
            report.add_table(
                heading,
                headers=item.get("headers", []),
                rows=item.get("rows", []),
            )

        elif item_type == "bar_chart":
            report.add_bar_chart(
                title=heading or item.get("title", ""),
                categories=item.get("categories", []),
                series_name=item.get("series_name", ""),
                values=item.get("values", []),
            )

        elif item_type == "pie_chart":
            report.add_pie_chart(
                title=heading or item.get("title", ""),
                data=item.get("data", []),
            )

        elif item_type == "note":
            report.add_note(item.get("content", ""))

        elif item_type == "references":
            report.add_references(item.get("entries", []))

    return report.build()


# 延迟导入避免循环
import re
